sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: wUUl4FBPwVdlSCkT+pgVeW/HBEuwgSn9bMU0xD0cPu9SlYt1b+HB94Agu7bfRRUZSkFKP7SXtbuhP1dYOvYZkeHsNCaCDxWm+f/9LxRbgSUPwfhBLwJKNUx/LQwqoiUqDuEI2bT3nA5N1+ulZuO5y+Olzl83Rt2rF3chdXIOgUfcCMwNS8UWnt8hUz6j/Ecq0Rb78L5PdI8trk4KgpLz5ITPqAcmbyCOp0ymzU89LwOpDZqwSpxhfz10Hv+y9hE9Lp03IGMVCYkowscsIYy+YRTAZYobFIeohN8fWXRZukRFunuzGGH8nby+xjH6/9U/EVGtH2akAZwz403SzDSypCpmDu1OKFFdOp2KW6VAa+Ve2WIrVDoHgnGWuRxCecfuw8TPNLXEGBRWW5whA9BMT4H2/1sOE2IlqU2qAnktFXiBcppsC54ASKh2Z+a5wgofEGaJI1zpFTRAHMo0sO8QR6OB5brTxJdhRCwLsCP1VBMDSs57g/nUMdq6kp37hGtOhE8Q/fViG2fk7UE4x9Nk6YpSLjvUVWjhtyl80yK5xqUcliVv+/H2R4ya7uvSaQMJdKMc+wKCkChM36Ucbxbgln1TTmoY6z+AuOL8uIJ0QZ6EQNqHno1dMG59yE6ImfRcdFPARAtlEAT1CmiVOKO9JjMUG3tuIRqAnF9LD7DU9cY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Seven-Wives-and-Seven-Prisons--13-Or-Experiences-in-the-Life-of-a-Matrimonial-Monomaniac.-A-Tr__4667
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy